# Travis CI config
language: php
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
matrix:
  fast_finish: true
  include:
  - php: 7.0
  - php: 7.1
  - php: 7.2
  - php: nightly
  allow_failures:
  - php: 7.0
  - php: 7.1
  - php: nightly

before_install:
  - composer self-update

install:
  composer install --prefer-dist

script:
  composer test
